// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Collection struct {
	ID   string  `json:"id"`
	User *User   `json:"user"`
	Game []*Game `json:"game"`
}

type Game struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Yearpublished string  `json:"yearpublished"`
	Playingtime   int     `json:"playingtime"`
	Minplayers    int     `json:"minplayers"`
	Maxplayers    int     `json:"maxplayers"`
	Score         float64 `json:"score"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
